In [1]:
import numpy as np
import pandas as pd
from pandas import read_csv as rc

In [2]:
import matplotlib.pyplot as plt

In [5]:
housing_data=rc(r"D:\yohesha\Code Casa Internship\Housing.csv")

In [45]:
housing_data

price  area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
0    13300000  7420         4          2        3        2          True   
1    12250000  8960         4          4        4        3          True   
2    12250000  9960         3          2        2        2          True   
3    12215000  7500         4          2        2        3          True   
4    11410000  7420         4          1        2        2          True   
..        ...   ...       ...        ...      ...      ...           ...   
540   1820000  3000         2          1        1        2          True   
541   1767150  2400         3          1        1        0         False   
542   1750000  3620         2          1        1        0          True   
543   1750000  2910         3          1        1        0         False   
544   1750000  3850         3          1        2        0          True   

     guestroom_yes  basement_yes  airconditioning_yes  hotwaterheating_yes  \
0            False         False                 True                False   
1            False         False                 True                False   
2            False          True                False                False   
3            False          True                 True                False   
4             True          True                 True                False   
..             ...           ...                  ...                  ...   
540          False          True                False                False   
541          False         False                False                False   
542          False         False                False                False   
543          False         False                False                False   
544          False         False                False                False   

     prefarea_yes  furnishingstatus_semi-furnished  \
0            True                            False   
1           False                            False   
2            True                             True   
3            True                            False   
4           False                            False   
..            ...                              ...   
540         False                            False   
541         False                             True   
542         False                            False   
543         False                            False   
544         False                            False   

     furnishingstatus_unfurnished  
0                           False  
1                           False  
2                           False  
3                           False  
4                           False  
..                            ...  
540                          True  
541                         False  
542                          True  
543                         False  
544                          True  

[545 rows x 14 columns]

In [8]:
housing_data=pd.get_dummies(housing_data,columns=['mainroad','guestroom','basement','airconditioning','hotwaterheating','prefarea','furnishingstatus'],drop_first=True)

In [46]:
housing_data.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [9]:
housing_data

price  area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
0    13300000  7420         4          2        3        2          True   
1    12250000  8960         4          4        4        3          True   
2    12250000  9960         3          2        2        2          True   
3    12215000  7500         4          2        2        3          True   
4    11410000  7420         4          1        2        2          True   
..        ...   ...       ...        ...      ...      ...           ...   
540   1820000  3000         2          1        1        2          True   
541   1767150  2400         3          1        1        0         False   
542   1750000  3620         2          1        1        0          True   
543   1750000  2910         3          1        1        0         False   
544   1750000  3850         3          1        2        0          True   

     guestroom_yes  basement_yes  airconditioning_yes  hotwaterheating_yes  \
0            False         False                 True                False   
1            False         False                 True                False   
2            False          True                False                False   
3            False          True                 True                False   
4             True          True                 True                False   
..             ...           ...                  ...                  ...   
540          False          True                False                False   
541          False         False                False                False   
542          False         False                False                False   
543          False         False                False                False   
544          False         False                False                False   

     prefarea_yes  furnishingstatus_semi-furnished  \
0            True                            False   
1           False                            False   
2            True                             True   
3            True                            False   
4           False                            False   
..            ...                              ...   
540         False                            False   
541         False                             True   
542         False                            False   
543         False                            False   
544         False                            False   

     furnishingstatus_unfurnished  
0                           False  
1                           False  
2                           False  
3                           False  
4                           False  
..                            ...  
540                          True  
541                         False  
542                          True  
543                         False  
544                          True  

[545 rows x 14 columns]

In [12]:
from sklearn.preprocessing import MinMaxScaler
columns=['mainroad_yes','guestroom_yes','basement_yes','airconditioning_yes','hotwaterheating_yes','prefarea_yes','furnishingstatus_semi-furnished','furnishingstatus_unfurnished']
scaler = MinMaxScaler()
data=pd.DataFrame(scaler.fit_transform(housing_data),columns=housing_data.columns)

In [13]:
data

price      area  bedrooms  bathrooms   stories   parking  \
0    1.000000  0.396564       0.6   0.333333  0.666667  0.666667   
1    0.909091  0.502405       0.6   1.000000  1.000000  1.000000   
2    0.909091  0.571134       0.4   0.333333  0.333333  0.666667   
3    0.906061  0.402062       0.6   0.333333  0.333333  1.000000   
4    0.836364  0.396564       0.6   0.000000  0.333333  0.666667   
..        ...       ...       ...        ...       ...       ...   
540  0.006061  0.092784       0.2   0.000000  0.000000  0.666667   
541  0.001485  0.051546       0.4   0.000000  0.000000  0.000000   
542  0.000000  0.135395       0.2   0.000000  0.000000  0.000000   
543  0.000000  0.086598       0.4   0.000000  0.000000  0.000000   
544  0.000000  0.151203       0.4   0.000000  0.333333  0.000000   

     mainroad_yes  guestroom_yes  basement_yes  airconditioning_yes  \
0             1.0            0.0           0.0                  1.0   
1             1.0            0.0           0.0                  1.0   
2             1.0            0.0           1.0                  0.0   
3             1.0            0.0           1.0                  1.0   
4             1.0            1.0           1.0                  1.0   
..            ...            ...           ...                  ...   
540           1.0            0.0           1.0                  0.0   
541           0.0            0.0           0.0                  0.0   
542           1.0            0.0           0.0                  0.0   
543           0.0            0.0           0.0                  0.0   
544           1.0            0.0           0.0                  0.0   

     hotwaterheating_yes  prefarea_yes  furnishingstatus_semi-furnished  \
0                    0.0           1.0                              0.0   
1                    0.0           0.0                              0.0   
2                    0.0           1.0                              1.0   
3                    0.0           1.0                              0.0   
4                    0.0           0.0                              0.0   
..                   ...           ...                              ...   
540                  0.0           0.0                              0.0   
541                  0.0           0.0                              1.0   
542                  0.0           0.0                              0.0   
543                  0.0           0.0                              0.0   
544                  0.0           0.0                              0.0   

     furnishingstatus_unfurnished  
0                             0.0  
1                             0.0  
2                             0.0  
3                             0.0  
4                             0.0  
..                            ...  
540                           1.0  
541                           0.0  
542                           1.0  
543                           0.0  
544                           1.0  

[545 rows x 14 columns]

In [14]:
data_y=data[['price']]

In [15]:
data_x=data.drop('price',axis=1)

In [16]:
data_x

area  bedrooms  bathrooms   stories   parking  mainroad_yes  \
0    0.396564       0.6   0.333333  0.666667  0.666667           1.0   
1    0.502405       0.6   1.000000  1.000000  1.000000           1.0   
2    0.571134       0.4   0.333333  0.333333  0.666667           1.0   
3    0.402062       0.6   0.333333  0.333333  1.000000           1.0   
4    0.396564       0.6   0.000000  0.333333  0.666667           1.0   
..        ...       ...        ...       ...       ...           ...   
540  0.092784       0.2   0.000000  0.000000  0.666667           1.0   
541  0.051546       0.4   0.000000  0.000000  0.000000           0.0   
542  0.135395       0.2   0.000000  0.000000  0.000000           1.0   
543  0.086598       0.4   0.000000  0.000000  0.000000           0.0   
544  0.151203       0.4   0.000000  0.333333  0.000000           1.0   

     guestroom_yes  basement_yes  airconditioning_yes  hotwaterheating_yes  \
0              0.0           0.0                  1.0                  0.0   
1              0.0           0.0                  1.0                  0.0   
2              0.0           1.0                  0.0                  0.0   
3              0.0           1.0                  1.0                  0.0   
4              1.0           1.0                  1.0                  0.0   
..             ...           ...                  ...                  ...   
540            0.0           1.0                  0.0                  0.0   
541            0.0           0.0                  0.0                  0.0   
542            0.0           0.0                  0.0                  0.0   
543            0.0           0.0                  0.0                  0.0   
544            0.0           0.0                  0.0                  0.0   

     prefarea_yes  furnishingstatus_semi-furnished  \
0             1.0                              0.0   
1             0.0                              0.0   
2             1.0                              1.0   
3             1.0                              0.0   
4             0.0                              0.0   
..            ...                              ...   
540           0.0                              0.0   
541           0.0                              1.0   
542           0.0                              0.0   
543           0.0                              0.0   
544           0.0                              0.0   

     furnishingstatus_unfurnished  
0                             0.0  
1                             0.0  
2                             0.0  
3                             0.0  
4                             0.0  
..                            ...  
540                           1.0  
541                           0.0  
542                           1.0  
543                           0.0  
544                           1.0  

[545 rows x 13 columns]

In [17]:
data_y

price
0    1.000000
1    0.909091
2    0.909091
3    0.906061
4    0.836364
..        ...
540  0.006061
541  0.001485
542  0.000000
543  0.000000
544  0.000000

[545 rows x 1 columns]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,Y_train,Y_test=train_test_split(data_x,data_y,test_size=0.4,random_state=40)

In [25]:
X_train

area  bedrooms  bathrooms   stories   parking  mainroad_yes  \
366  0.136082       0.2   0.000000  0.000000  0.000000           1.0   
401  0.539519       0.4   0.000000  0.333333  1.000000           1.0   
358  0.125773       0.2   0.000000  0.000000  0.000000           1.0   
302  0.034021       0.4   0.000000  0.666667  0.333333           1.0   
501  0.053608       0.4   0.000000  0.000000  0.000000           0.0   
..        ...       ...        ...       ...       ...           ...   
440  0.136770       0.6   0.000000  0.333333  0.000000           1.0   
165  0.329897       0.4   0.333333  0.000000  0.000000           1.0   
7    1.000000       0.8   0.666667  0.333333  0.000000           1.0   
219  0.367698       0.4   0.000000  0.333333  0.000000           1.0   
326  0.168385       0.6   0.000000  0.000000  0.000000           0.0   

     guestroom_yes  basement_yes  airconditioning_yes  hotwaterheating_yes  \
366            0.0           1.0                  0.0                  0.0   
401            0.0           0.0                  0.0                  0.0   
358            0.0           0.0                  0.0                  0.0   
302            0.0           0.0                  0.0                  0.0   
501            0.0           0.0                  0.0                  0.0   
..             ...           ...                  ...                  ...   
440            0.0           1.0                  0.0                  0.0   
165            1.0           1.0                  0.0                  1.0   
7              0.0           0.0                  0.0                  0.0   
219            0.0           1.0                  0.0                  0.0   
326            0.0           1.0                  0.0                  0.0   

     prefarea_yes  furnishingstatus_semi-furnished  \
366           0.0                              0.0   
401           1.0                              0.0   
358           1.0                              1.0   
302           1.0                              0.0   
501           0.0                              0.0   
..            ...                              ...   
440           0.0                              0.0   
165           0.0                              0.0   
7             0.0                              0.0   
219           0.0                              0.0   
326           0.0                              0.0   

     furnishingstatus_unfurnished  
366                           0.0  
401                           1.0  
358                           0.0  
302                           1.0  
501                           1.0  
..                            ...  
440                           1.0  
165                           1.0  
7                             1.0  
219                           1.0  
326                           1.0  

[327 rows x 13 columns]

In [27]:
from sklearn.neighbors import KNeighborsRegressor

In [28]:
import math
math.sqrt(545)
#this is to find no of neighbors to be assigned
#This is calculated by taking the square root of the number of rows present in the entire dataset

23.345235059857504

In [29]:
# Neighbor value = 23
n_neighbors=23

In [30]:
knn_regressor=KNeighborsRegressor(n_neighbors)

In [31]:
knn_regressor.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=23)

In [32]:
knn_predictions=knn_regressor.predict(X_test)

In [33]:
knn_predictions

array([[0.35333123],
       [0.33015599],
       [0.39795573],
       [0.13783926],
       [0.20458498],
       [0.10812912],
       [0.16746904],
       [0.24960474],
       [0.36032938],
       [0.0973386 ],
       [0.27645586],
       [0.10508564],
       [0.1873913 ],
       [0.1783386 ],
       [0.3997365 ],
       [0.1783386 ],
       [0.2785112 ],
       [0.40363636],
       [0.21565217],
       [0.0973386 ],
       [0.10719368],
       [0.10279315],
       [0.19067194],
       [0.38862978],
       [0.0973386 ],
       [0.09862978],
       [0.23957839],
       [0.13061924],
       [0.21100264],
       [0.19924901],
       [0.25335968],
       [0.28290962],
       [0.21140975],
       [0.10508564],
       [0.34400527],
       [0.13391304],
       [0.10411067],
       [0.27679842],
       [0.1873913 ],
       [0.10139657],
       [0.28696759],
       [0.20911726],
       [0.36990567],
       [0.37772069],
       [0.39657233],
       [0.25080369],
       [0.17823452],
       [0.241

In [34]:
from sklearn.metrics import mean_squared_error

In [35]:
MSE=mean_squared_error(Y_test,knn_predictions)

In [36]:
MSE

0.018760387804638963

In [77]:
rmse=np.sqrt(MSE)
rmse

0.1369685650236541

In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(Y_test,knn_predictions)

0.4142317680166857

In [43]:
from sklearn.metrics import mean_absolute_error

In [44]:
mean_absolute_error(Y_test,knn_predictions)

0.0901890403838948

In [47]:
from sklearn.linear_model import LinearRegression

In [48]:
LR_housing=LinearRegression()

In [49]:
LR_housing.fit(X_train,Y_train)

LinearRegression()

In [50]:
LR_predictions=LR_housing.predict(X_test)

In [51]:
LR_predictions

array([[0.46268156],
       [0.39938463],
       [0.52157714],
       [0.13479106],
       [0.26550239],
       [0.09210942],
       [0.29257503],
       [0.16287403],
       [0.4001917 ],
       [0.10046326],
       [0.41061669],
       [0.12776651],
       [0.14451187],
       [0.11584981],
       [0.54889481],
       [0.07198354],
       [0.28934257],
       [0.48203624],
       [0.19891369],
       [0.08518668],
       [0.13781689],
       [0.11011424],
       [0.13380197],
       [0.31640019],
       [0.09322698],
       [0.04065386],
       [0.2099575 ],
       [0.27289921],
       [0.16434394],
       [0.1910995 ],
       [0.23992031],
       [0.4072496 ],
       [0.40726098],
       [0.12274131],
       [0.45656403],
       [0.13040216],
       [0.12847753],
       [0.3086418 ],
       [0.19600123],
       [0.09761536],
       [0.34610488],
       [0.23151767],
       [0.45807347],
       [0.37058027],
       [0.42263046],
       [0.27714543],
       [0.12224011],
       [0.423

In [75]:
mse_LR=mean_squared_error(Y_test,LR_predictions)
mse_LR

0.011420761284573044

In [79]:
rmse=math.sqrt(mse_LR)
rmse

0.10686796191830854

In [56]:
from sklearn.linear_model import Ridge

In [58]:
alpha=1.0

In [59]:
ridge_regressor_housing=Ridge(alpha)

In [61]:
ridge_regressor_housing.fit(X_train,Y_train)

Ridge()

In [63]:
Ridge_regressor_predictions=ridge_regressor_housing.predict(X_test)

In [64]:
Ridge_regressor_predictions

array([[0.45443624],
       [0.39433088],
       [0.51557163],
       [0.13588575],
       [0.26692221],
       [0.09838629],
       [0.28076641],
       [0.17231963],
       [0.39522031],
       [0.10187743],
       [0.40389579],
       [0.13195063],
       [0.1504284 ],
       [0.12031756],
       [0.54072497],
       [0.07588705],
       [0.28883502],
       [0.47783502],
       [0.20714964],
       [0.08863525],
       [0.14066259],
       [0.11351374],
       [0.13934926],
       [0.31723586],
       [0.09560482],
       [0.04491338],
       [0.21734905],
       [0.26295789],
       [0.17060791],
       [0.19970777],
       [0.23856056],
       [0.39749034],
       [0.38454396],
       [0.12759464],
       [0.45015799],
       [0.13655287],
       [0.13189537],
       [0.3031233 ],
       [0.19752466],
       [0.10581474],
       [0.34538021],
       [0.23316082],
       [0.44916515],
       [0.37077424],
       [0.42370699],
       [0.27811663],
       [0.12784874],
       [0.413

In [82]:
mse_Ridge_regressor=mean_squared_error(Y_test,Ridge_regressor_predictions)
mse_Ridge_regressor

0.011524635946793416

In [83]:
ridge_regressor_housing.coef_

array([[ 0.25351813,  0.02639418,  0.25141954,  0.10051896,  0.06764644,
         0.03575852,  0.04068137,  0.02028377,  0.08161511,  0.05814439,
         0.04462538,  0.00580031, -0.028359  ]])

In [84]:
ridge_regressor_housing.intercept_

array([0.04128328])

In [85]:
rmse=math.sqrt(mse_Ridge_regressor)
rmse

0.10735285718970602